import assert from "node:assert/strict";
import test from "node:test";
import {
  developmentMakefile,
  parseAppleDevelopmentIdentities,
  selectDevelopmentTeam,
} from "./configure-development-signing.mjs";

test("Apple Development identities resolve to unique team identifiers", () => {
  const output = `
  1) AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "Apple Development: Alex Example (TEAMID1234)"
  2) BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB "Apple Development: Alex Example (TEAMID1234)"
     2 valid identities found
  `;
  assert.deepEqual(parseAppleDevelopmentIdentities(output), ["TEAMID1234"]);
});

test("signing selection fails closed for absent and ambiguous identities", () => {
  assert.throws(() => selectDevelopmentTeam([]), /No valid Apple Development/);
  assert.throws(
    () => selectDevelopmentTeam(["TEAMID1234", "OTHERID567"]),
    /Multiple Apple Development teams/,
  );
  assert.throws(
    () => selectDevelopmentTeam(["TEAMID1234"], "OTHERID567"),
    /No valid Apple Development identity is installed/,
  );
});

test("the selected team is persisted as non-secret local make configuration", () => {
  assert.equal(selectDevelopmentTeam(["TEAMID1234"]), "TEAMID1234");
  assert.equal(
    developmentMakefile("TEAMID1234"),
    "# Generated by Scripts/configure-development-signing.mjs; do not commit.\n"
      + "SCOUT_DEVELOPMENT_TEAM := TEAMID1234\n",
  );
});
